version: "3.9"

services:
  goalflow-postgres:
    container_name: goalFlow-postgres
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: app
    ports:
      - "25431:5432"
    volumes:
      - goalflow_postgres_data:/var/lib/postgresql/data

volumes:
  goalflow_postgres_data:
